defaults:
  - teamtr_base_lora
  - _self_

trainer:
  experiment_name: teamtr_homo_lora

actor_rollout_ref:
  model:
    path: ./models/Qwen__Qwen3-8B
  rollout:
    agent_model_paths:
      - ./models/Qwen__Qwen3-8B
      - ./models/Qwen__Qwen3-8B
      - ./models/Qwen__Qwen3-8B
